stages:
  - build
  - deploy


build_site:
  stage: build
  image:
    name: squidfunk/mkdocs-material
    entrypoint: [""]
  script:
    - mkdocs build
  artifacts:
    paths:
      - site/

deploy_site:
  stage: deploy
  image: alpine
  only:
    - master
  script:
    - which ssh-agent || apk --update add openssh-client
    - which rsync || apk --update add rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - rsync -vzrl --chown=gitlab-runner:gitlab-runner --del -e 'ssh -o StrictHostKeyChecking=no' site/ gitlab-runner@www.eidos.ic.i.u-tokyo.ac.jp:/var/www/eidos/
